name: Post-step action

description: 'Allows composite GitHub Actions to define a post-run step.'

branding:
  icon: anchor
  color: gray-dark

inputs:
  post:
    description: 'Post command/script.'
    required: true

runs:
  using: 'node20'
  main: 'main.js'
  post: 'post.js'
